### ISSUE TITLE
Review addresses backlog and issues for potential contributions

### ISSUE THREAD

**Issue by timpaul** [alphagov/govuk-design-system#1392] opened 2020-10-27 12:29 UTC
Use the pilot process here: https://github.com/alphagov/govuk-design-system-backlog/issues/221

**Comment by timpaul** [comment] 2020-10-27 12:29
CHECKLIST

- [ ] hide any outdated, off-topic or resolved comments
- [ ] capture significant research findings and raise PRs for the 'Research' section of the guidance
- [ ] capture significant design decisions and raise PRs for the 'How it works' section of the guidance
- [ ] capture issues, bugs and feature requests and raise issues for them in the appropriate repo
- [ ] search the repos and add the item label to any relevant issues and PRs that are missing them
- [ ] update the initial comment with links and last reviewed date
- [ ] decide whether the item should still be experimental
- [ ] set a review reminder for 6(?) months in the future

**Comment by timpaul** [comment] 2020-10-27 12:31
LINKS

### Links
- [view this component in the GOV.UK Design System](https://govuk-design-system-production.cloudapps.digital/patterns/addresses)
- [view a list of open issues and pull requests for this component](https://github.com/search?q=label%3A%22addresses%22+is%3Aopen+repo%3Aalphagov%2Fgovuk-design-system+repo%3Aalphagov%2Fgovuk-frontend+repo%3Aalphagov%2Fgovuk-prototype-kit&type=issues)
- [view the commit history of the guidance for this component](https://github.com/alphagov/govuk-design-system/commits/master/src/patterns/addresses)
- [view the commit history of the code for this component](https://github.com/alphagov/govuk-frontend/commits/master/src/govuk/patterns/addresses)

**Comment by kellylee-gds** [comment] 2020-10-29 10:11
Closed as a duplicate of https://github.com/alphagov/govuk-design-system/issues/1190

**Closed by kellylee-gds** 2020-10-29 10:11 UTC
