### ISSUE TITLE
WCAG 2.2: Page template/footer ‖ Consistent Help

### ISSUE THREAD

**Issue by querkmachine** [alphagov/govuk-design-system#2871] opened 2023-06-22 14:37 UTC
## What

Add to our guidance on the page template and/or footer pages to emphasise that help links should appear consistently and in the same location, no matter where a user is in the service. 

### Resources

- [Page template styles page](https://design-system.service.gov.uk/styles/page-template/)
- [Footer component page](https://design-system.service.gov.uk/components/footer/)
- [WCAG 2.2 criterion for 'Consistent Help'](https://www.w3.org/WAI/WCAG22/Understanding/consistent-help.html)

## Why

The new WCAG 2.2 Level A criterion 'Consistent Help' says: 

> If a [Web page](https://www.w3.org/WAI/WCAG22/Understanding/consistent-help.html#dfn-web-page) contains any of the following help [mechanisms](https://www.w3.org/WAI/WCAG22/Understanding/consistent-help.html#), and those mechanisms are repeated on multiple Web pages within a [set of Web pages](https://www.w3.org/WAI/WCAG22/Understanding/consistent-help.html#dfn-set-of-web-pages), they occur in the same order relative to other page content, unless a change is initiated by the user:
> * Human contact details;
> * Human contact mechanism;
> * Self-help option;
> * A fully automated contact mechanism.

The intent of this criterion is to ensure that a user can find help when completing tasks on a webpage. We have interpreted this as meaning that a link to help or contact information:

- Should appear on most, if not all, pages on a service.
- Should appear in the same place on each of those pages (most likely, but not necessarily, in the footer).

## Who needs to work on this
- Content designer or technical writer

## Who needs to review this
- Accessibility specialist
- Content designer or technical writer

## Done when

- [ ] Decided which guidance page this content is most suited to
- [ ] Guidance has been updated

**Comment by dav-idc** [comment] 2023-10-25 14:47
This issue appears to already be covered by the existing planned guidance updates in the WCAG 2.2 content updates main guidance doc.
Here's the existing section that covers footers and consistent help: https://docs.google.com/document/d/1nIxIKgVUheC8zvVdqWIcqtVPCl7oTN4hv11R9rDwdvM/edit#heading=h.varqk0aj5n9z

As a result I'm closing this issue as a duplicate of the main WCAG 2.2 guidance issue:
- https://github.com/alphagov/govuk-design-system/issues/2729
- https://github.com/alphagov/govuk-design-system/pull/3090

**Closed by dav-idc** 2023-10-25 14:47 UTC
Labels: accessibility, page template, footer, WCAG 2.2
