### ISSUE TITLE
Component sandbox - Allow component examples to be modified based on pre-sets and user content

### ISSUE THREAD

**Issue by dashouse** [alphagov/govuk-design-system#853] opened 2019-04-12 06:20 UTC
Allow component examples to be modified in the design system so that:
- The default example is not seen as a hard requirement or only acceptable configuration
- The user can see how the component will look with their content
- All component options will be exposed, reducing duplication of features

Here's a very simple example I put together in Codepen
![54608708-34c67480-4a49-11e9-9fb5-8aee0068e5b8](https://user-images.githubusercontent.com/23356842/56016286-a49be800-5cf3-11e9-8045-8d022445fc0b.gif)

This was part of the original design of the component preview but was de-scoped.

## Examples in other Design Systems

**Morningstar**
<img width="1017" alt="Screen Shot 2019-04-12 at 07 28 25" src="https://user-images.githubusercontent.com/23356842/56016633-d06b9d80-5cf4-11e9-870b-de38341f2a4a.png">

**Lightning Design System**
<img width="946" alt="Screen Shot 2019-04-12 at 07 24 16" src="https://user-images.githubusercontent.com/23356842/56016401-08261580-5cf4-11e9-947d-a06fefbf5dcb.png">

**Polaris design system**
<img width="780" alt="Screen Shot 2019-04-12 at 07 23 54" src="https://user-images.githubusercontent.com/23356842/56016408-0e1bf680-5cf4-11e9-9c92-5425248b6b2c.png">

**Carbon design system** - A less integrated sandbox linking out to Codepen
<img width="1018" alt="Screen Shot 2019-04-12 at 07 27 08" src="https://user-images.githubusercontent.com/23356842/56016721-1f193780-5cf5-11e9-8442-6a1a32f6e08f.png">

**Comment by trang-erskine** [comment] 2020-09-04 09:46
Closed - duplicate of #1108

**Closed by trang-erskine** 2020-09-04 09:46 UTC
Labels: 🕔 weeks
