### ISSUE TITLE
Include 'focus' in search

### ISSUE THREAD

**Issue by edwardhorsford** [alphagov/govuk-design-system#1082] opened 2019-11-12 15:00 UTC
Would it be possible to include 'focus' in the search?

I completely missed the guide to focus - I checked every section except 'getting started' (which I think seemed the least likely place) - and searched in the header.

**Comment by nickcolley** [comment] 2019-11-12 15:03
Closing this as a duplicate of https://github.com/alphagov/govuk-design-system/issues/1062 but thank you for letting us know this was hard to find

**Closed by nickcolley** 2019-11-12 15:03 UTC
