### ISSUE TITLE
WCAG 2.2: Question pages ‖ Redundant entry

### ISSUE THREAD

**Issue by querkmachine** [alphagov/govuk-design-system#2866] opened 2023-06-22 10:51 UTC
## What

Update our guidance on asking questions to emphasise that services should not request information that has already been provided or have stored, unless doing so is necessary for security purposes or the information is out of date. 

### Resources

- [Question pages guidance](https://design-system.service.gov.uk/patterns/question-pages/)
- [WCAG 2.2 criterion for 'Redundant entry'](https://www.w3.org/WAI/WCAG22/Understanding/redundant-entry.html)

## Why

The new WCAG 2.2 criterion 'Redundant entry' says: 

> Information previously entered by or provided to the user that is required to be entered again in the same [process](https://www.w3.org/WAI/WCAG22/Understanding/redundant-entry.html#dfn-process) is either:
> 
> - auto-populated, or
> - available for the user to select.

This could potentially cover several patterns. Patterns that were identified as being potentially relevant during desk research include:

- [Create a username](https://design-system.service.gov.uk/patterns/create-a-username/)
- [Confirm an email address](https://design-system.service.gov.uk/patterns/confirm-an-email-address/)
- [Confirm a phone number](https://design-system.service.gov.uk/patterns/confirm-a-phone-number/)
- [Passwords](https://design-system.service.gov.uk/patterns/passwords/)
- [Payment card details](https://design-system.service.gov.uk/patterns/payment-card-details/)
- [Dates](https://design-system.service.gov.uk/patterns/dates/)
- [Gender or sex](https://design-system.service.gov.uk/patterns/gender-or-sex/)
- [Telephone numbers](https://design-system.service.gov.uk/patterns/telephone-numbers/)

To avoid needing to update all of these patterns individually, the intent is to consolidate the guidance updates on the 'Question pages' page instead. 

## Who needs to work on this
Content designer or technical writer

## Who needs to review this
Accessibility specialist, content designer or technical writer

## Done when

- [ ] Guidance has been updated

**Comment by dav-idc** [comment] 2023-10-25 10:12
This issue is tracked in the [WCAG 2.2 content updates document (restricted)](https://docs.google.com/document/d/1nIxIKgVUheC8zvVdqWIcqtVPCl7oTN4hv11R9rDwdvM/edit?usp=sharing).

**Comment by dav-idc** [comment] 2023-10-25 14:57
This issue appears to already be covered by the existing planned guidance updates in the WCAG 2.2 content updates main guidance doc.
Here's the existing section that covers footers and consistent help: https://docs.google.com/document/d/1nIxIKgVUheC8zvVdqWIcqtVPCl7oTN4hv11R9rDwdvM/edit#heading=h.x6h6ome4vh0o

As a result I'm closing this issue as a duplicate of the main WCAG 2.2 guidance issue:
- https://github.com/alphagov/govuk-design-system/issues/2729
- https://github.com/alphagov/govuk-design-system/pull/3090

**Closed by dav-idc** 2023-10-25 14:57 UTC
Labels: accessibility, question pages, WCAG 2.2
