### ISSUE TITLE
Document how to set widths of columns for summary list

### ISSUE THREAD

**Issue by hannalaakso** [alphagov/govuk-design-system#1079] opened 2019-11-06 14:04 UTC
A user asked how to set the column widths for the summary list component. We have an example of doing this with the [width override classes](http://govuk-frontend-review.herokuapp.com/components/summary-list/overridden-widths/preview) in our review app but it's not documented in the Design System.

**Comment by 36degrees** [comment] 2020-05-04 12:42
Closing as a duplicate of #1196

**Closed by 36degrees** 2020-05-04 12:42 UTC
Labels: documentation, submitted by user, 🕔 hours
