### ISSUE TITLE
It's not clear how and when to use links styled as buttons

### ISSUE THREAD

**Issue by joelanman** [alphagov/govuk-design-system#929] opened 2019-06-20 13:33 UTC
https://design-system.service.gov.uk/components/button/

The only reference to links as buttons is in the Macro arguments:

```
href | string | The URL that the button should link to. If this is set, element will be automatically set to a if it has not already been defined.
```

Links as buttons are useful if you need a 'Continue' button on a page where there's no data to submit, and they're useful in prototyping where you may be faking the data part of the prototype.

We could mention how to do them, and when/when not to use.

**Comment by timpaul** [comment] 2019-06-26 13:23
Following triage, we've decided to add "link button" guidance to the buttons page, explaining when and when not to use them.

**Comment by 36degrees** [comment] 2020-05-04 12:46
Closing as a duplicate of #1185

**Closed by 36degrees** 2020-05-04 12:46 UTC
Labels: submitted by user, 🕔 hours
