### ISSUE TITLE
Add guidance for text alignment classes

### ISSUE THREAD

**Issue by hannalaakso** [alphagov/govuk-design-system#1897] opened 2021-09-27 09:35 UTC
## What

We added some new classes for aligning text in https://github.com/alphagov/govuk-frontend/issues/1824. We should add some corresponding guidance to the Design System for these classes.

## Why

To help our users discover the classes and understand how to use them

## Who needs to know about this

Developer, content writer

## Done when

- [ ] New guidance PR raised and approved (not yet merged)
- [ ] PR merged in after GOV.UK Frontend 3.14.0 is released

**Comment by hannalaakso** [comment] 2021-09-27 09:43
Draft guidance here: https://docs.google.com/document/d/1XM2qX_CZ99RuiJzs-DKK_-_xTXvuRbbqJ40Jpaouqag/edit#

**Comment by 36degrees** [comment] 2021-09-29 08:37
Closing as a dupe of #1863.

**Closed by 36degrees** 2021-09-29 08:37 UTC
Labels: guidance
