### ISSUE TITLE
Design System website opens top menu items in new tabs on iPads running the Firefox browser

### ISSUE THREAD

**Issue by wilsond-gds** [alphagov/govuk-design-system#2201] opened 2022-05-23 11:19 UTC
## Description of the issue
If a user is using the Firefox browser on an iPad, when they choose an option on the top menu of [the Design System website](https://design-system.service.gov.uk/) the requested page opens in a new browser tab ‘behind’ the current page. See screenshot

![design system navigation error on iPad](https://user-images.githubusercontent.com/101639632/169808055-a7bf3f59-5a7a-4c58-b41c-64ccc122779b.jpeg)

## Steps to reproduce the issue

Go to [the Design System website](https://design-system.service.gov.uk/) while running the firefox browser on an iPad and choose a page from the top nav.

## Actual vs expected behaviour

The page should open in the same window

## Environment (where applicable)

iPad Air, Firefox browser app (build I believe is Daylight 100.1 9384)

- Operating system: iOS 15.4.1
- Browser: Firefox
- Browser version: 100.1 9384

**Comment by querkmachine** [comment] 2022-05-23 11:27
I just gave this a quick go as I happened to have my iPad Air in front of me, and I've not been able to reproduce the problem.

There's [some fairly recent complaints](https://support.mozilla.org/en-US/questions/1364961) of the issue you describe on Mozilla's support forum. Do you only see the problem on the Design System site? 

Also, are you using an external keyboard? It seems like [there is some buggy behaviour in Firefox](https://support.mozilla.org/en-US/questions/1331571) associated with that, too.

**Comment by querkmachine** [comment] 2023-08-21 09:41
I'm going to close this off as I've still been unable to reproduce it and we've had no other reports of this happening in over a year.

**Closed by querkmachine** 2023-08-21 09:41 UTC
Labels: 🐛 bug, website
