### ISSUE TITLE
Duplicate layouts on pages

### ISSUE THREAD

**Issue by alex-page** [alphagov/govuk-design-system#653] opened 2018-11-29 03:44 UTC
https://github.com/alphagov/govuk-design-system/blob/45ec6cb9c4d3b73ebc5fb73b221e54c585c77cc1/src/patterns/start-pages/index.md.njk#L17

https://github.com/alphagov/govuk-design-system/blob/45ec6cb9c4d3b73ebc5fb73b221e54c585c77cc1/src/patterns/start-pages/index.md.njk#L41

Hey friends ❤️ I was browsing your lovely design system and I noticed that some pages have duplicated examples. This might be intentional but it was super confusing to me as a user trying to figure what the difference was between the examples.

**Comment by dashouse** [comment] 2019-01-08 13:05
Hey @alex-page,

Thanks for your comment, sorry it's taken us a while to get back to you.

This is a bit of design debt that's related to the original intent to keep the content pattern of all items in the design system the same. We realise it doesn't really work for full page examples and we have a card to update it.

Because this issue is a duplicate of an internal task I will close it now, but thanks so much for raising. Hope all is well with you and the AU team!

**Closed by dashouse** 2019-01-08 13:05 UTC
Labels: discussion

**Comment by alex-page** [comment] 2019-01-08 22:30
No worries, thanks @dashouse 👍
