### ISSUE TITLE
Make examples in the Design System configurable

### ISSUE THREAD

**Issue by timpaul** [alphagov/govuk-design-system#1108] opened 2019-12-21 16:56 UTC
## What

Help users understand how each component can be modified within a set of pre-defined options. 

## Why

This will help reduce users thinking they need everything to be exactly as it appears in the design system (e.g. each question being an h1 and xl size even if on the same page). 

A secondary idea would be allow users to adapt the content to see the component with their own content and copy that.

VERY scrappy prototype here - https://codepen.io/iknowdavehouse/pen/ywEZPy

**Comment by 36degrees** [comment] 2019-12-23 15:10
@timpaul I think this is a duplicate of #853?

**Comment by stevenjmesser** [comment] 2024-01-15 10:21
Duplicate.

**Closed by stevenjmesser** 2024-01-15 10:21 UTC
Labels: epic
