### ISSUE TITLE
Design System Users Research

### ISSUE THREAD

**Issue by Katrina-Birch** [alphagov/govuk-design-system#3625] opened 2024-03-01 12:06 UTC
### What
Research into Design System users - those who work in service teams building citizen facing and internal services to understand the context in which they work. Focussing on users who aren’t very experienced in their discipline or those whose use of the Design System is limited through lack of knowledge, limited access or lower digital capability.

### Why
The context in which users work greatly affects their ability to access the Design System, learn about how to use it and access support from the community to help them understand how to make the best use of it.
In the absence of any formal Design System training, access to community support is essential for optimal use of the DS. Users learn from each other, seek answers to questions and problems, discuss issues and share examples of work. Community support can be provided by other users in the community, as well as the Design System team. It is something which exists with the encouragement of the Design System team, but is largely external to it.  Users access support through channels such as Slack and GitHub. 

### Who
User researcher

```[tasklist]
### Plan research
- [x] Write research plan
- [ ] Book in analysis sessions
- [ ] Book in Show and Tell
```

```[tasklist]
### Recruit
- [ ] Recruit participants
- [ ] Gain and record consent
- [ ] Agree and book research sessions
```

```[tasklist]
### Research
- [ ] Do interviews
- [ ] Collate findings
```

```[tasklist]
### Analyse and Share
- [ ] Analyse
- [ ] Create artefacts
- [ ] Write sharing deck
- [ ] Share insights at Show and Tell
```

**Comment by kellylee-gds** [comment] 2024-06-19 15:14
Closed as duplicate of #3730

**Closed by kellylee-gds** 2024-06-19 15:14 UTC
Labels: research, research ops
