### ISSUE TITLE
Scrollbar indicators are missing in Edge/IE11

### ISSUE THREAD

**Issue by nickcolley** [alphagov/govuk-design-system#468] opened 2018-08-03 12:47 UTC
On the homepage there's a visible scrollbar:
<img width="1440" alt="screen shot 2018-08-03 at 13 46 18" src="https://user-images.githubusercontent.com/2445413/43643582-a4354758-9723-11e8-88de-a2a220bae672.png">

But on pages with scrollable sections, it's not there, which could be confusing for windows users (where hidden scrollbars are not commonplace)
<img width="1440" alt="screen shot 2018-08-03 at 13 46 25" src="https://user-images.githubusercontent.com/2445413/43643583-a44fd618-9723-11e8-93be-d1520848ccd4.png">

**Comment by igloosi** [comment] 2018-08-07 14:47
caused by https://developer.mozilla.org/en-US/docs/Web/CSS/-ms-overflow-style on 
`.app-pane__body {  > *`

**Comment by nickcolley** [comment] 2018-08-07 14:50
https://github.com/alphagov/govuk-design-system/blob/f5df267e6d2582ff0a74eee8df59f8462e0b2538/src/stylesheets/components/_pane.scss#L45

**Comment by hannalaakso** [comment] 2018-08-13 10:45
This is also discussed here: https://trello.com/c/41Uv0QxI

**Comment by igloosi** [comment] 2018-11-01 11:09
fixed by #615

**Closed by igloosi** 2018-11-01 11:09 UTC
