### ISSUE TITLE
Example component on mobile viewport

### ISSUE THREAD

**Issue by dashouse** [alphagov/govuk-design-system#145] opened 2018-01-19 16:15 UTC
A couple of issues regarding the example component on mobile.

- "Resize" should be removed on mobile as a user cannot resize
- HTML "tab" is visible in accordion view at all times - In tab view this is removed when just showing HTML

**Comment by nickcolley** [comment] 2018-06-21 15:32
1. We have removed 'resize' based on the accessibility audit
2. I can't reproduce.

Will close this out, please re-open with a screenshot / more information if this is still happening :)

**Comment by nickcolley** [comment] 2018-06-22 09:18
@dashouse thanks for the screenie

**Closed** 2018-06-27 10:46 UTC
